settings:
  married_prefix: '&c[已婚]'
  unmarried_prefix: '&f[未婚]'
  marry_spend_money: 6666
  marry_spend_points: 15
  #bossshop的店名
  info_shop_name: 'CreeperMarriageInfoShop'
  #缓存期限,15分钟,单位s
  cache_livetime: 900 